// Generated by CoffeeScript 1.3.3
(function() {
  var Connection, Db, Model, Server, app, express, format, mongo;

  mongo = require('mongodb');

  Db = mongo.Db;

  Connection = mongo.Connection;

  Server = mongo.Server;

  format = require('util').format;

  Model = function(cb) {
    return Db.connect(format("mongodb://%s:%s/guo-fm-production?w=1", "127.0.0.1", 27017), function(err, db) {
      var Item;
      Item = db.collection('items');
      return Item.find().toArray(function(err, items) {
        return console.log(items.length);
      });
    });
  };

  express = require('express');

  app = express();

  app.get("/", function(req, res) {
    return res.send("hello");
  });

  app.listen(3000);

}).call(this);
